[package]
name = "escape-hatch"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[package.metadata.release]
release = false

[dependencies]
async-std = { version = "1.12", features = ["attributes"] }
async-trait = "0.1"
futures = "0.3.29"
futures-timer = "3.0.2"
libp2p = { path = "../../libp2p", features = [ "async-std", "ping"] }
libp2p-core = { workspace = true }
rand = "0.8"
tokio = { version = "1.33", features = ["macros", "net", "rt", "signal"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
void = "1.0"

[lints]
workspace = true